{% set name = "burst2safe" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/burst2safe-{{ version }}.tar.gz
  sha256: 27f00eb6b4933e473637477615a91a06f87b702886248a975a6c17174733d71f

build:
  entry_points:
    - burst2safe = burst2safe.burst2safe:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - shapely >=2
    - numpy <2.1.0
    - lxml
    - asf_search
    - tifffile >=2022.04.22
    - dateparser !=1.1.0
    - aiohttp

test:
  imports:
    - burst2safe
  commands:
    - pip check
    - burst2safe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A package for converting ASF-derived Sentinel-1 burst SLC products to the ESA SAFE format.
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/forrestfwilliams/burst2safe
  dev_url: https://github.com/forrestfwilliams/burst2safe
  doc_url: https://github.com/forrestfwilliams/burst2safe#burst2safe

extra:
  recipe-maintainers:
    - forrestfwilliams
