{% set name = "burst2safe" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/burst2safe-{{ version }}.tar.gz
  sha256: b2725ab3572ff558322d1cf255408fe89ca367d99cdb04c8aaf8096adb3bb446

build:
  entry_points:
    - burst2safe = burst2safe.burst2safe:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - gdal
    - shapely >=2
    - numpy
    - lxml
    - asf_search
    - tifffile

test:
  imports:
    - burst2safe
  commands:
    - pip check
    - burst2safe --help
  requires:
    - pip

about:
  summary: A package for converting ASF-derived Sentinel-1 burst SLC products to the ESA SAFE format.
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/forrestfwilliams/burst2safe
  dev_url: https://github.com/forrestfwilliams/burst2safe
  doc_url: https://github.com/forrestfwilliams/burst2safe#burst2safe

extra:
  recipe-maintainers:
    - forrestfwilliams
