{% set name = "burst2safe" %}
{% set version = "2.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/burst2safe-{{ version }}.tar.gz
  sha256: dafb6ff96e685ff6e703b8a52015e33a37371ffa0200432ea0c5e19f96c82077

build:
  entry_points:
    - burst2safe = burst2safe.burst2safe:main
    - burst2stack = burst2safe.burst2stack:main
    - local2safe = burst2safe.local2safe:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - shapely >=2.1.0
    - numpy
    - lxml
    - asf_search
    - tifffile >=2022.04.22
    - dateparser !=1.1.0
    - aiohttp >=3.12.6

test:
  imports:
    - burst2safe
  commands:
    - pip check
    - burst2safe --help
    - burst2stack --help
    - local2safe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A package for converting ASF-derived Sentinel-1 burst SLC products to the ESA SAFE format.
  license: BSD-2-Clause
  license_file: LICENSE
  home: https://github.com/ASFHyP3/burst2safe
  dev_url: https://github.com/ASFHyP3/burst2safe
  doc_url: https://github.com/ASFHyP3/burst2safe#burst2safe

extra:
  recipe-maintainers:
    - asjohnston-asf
    - jhkennedy
    - williamh890
    - jtherrmann
    - forrestfwilliams
